env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:mozilla/recommended

parserOptions:
  ecmaVersion: 8
  sourceType: module

plugins:
  - mozilla
  - promise
  - react

root: true

rules:
  consistent-return: error
  eqeqeq: error
  no-console: warn
  prefer-const: off # TODO: change to "error"
  quotes: [error, double]

  promise/always-return: off
  promise/avoid-new: off
  promise/catch-or-return: error
  promise/no-callback-in-promise: off
  promise/no-native: off
  promise/no-nesting: off
  promise/no-promise-in-callback: off
  promise/param-names: error
  react/prop-types: off

settings:
  react:
    version: 16
